### ISSUE TITLE
How to get facebook page key

### ISSUE THREAD

**Issue by KartikBazzad** [CJFreelancing/FacebookPageExample#2]
Thanks for developing this beautiful app
 
i wanna know how to get the Facebook Page key?
i have searched everywhere but i am unable to find whats a facebook page key?

**Comment by CJMobileApps** [comment]
@KartikBazzad for this part of the code right?

` public static String key = "";
private static String access_token = "&access_token="+key;`

It's been a while since I worked on this but I believe you need to set up a developer account for Facebook and get a key. Something like this -->  [Youtube Facebook Api key link](https://www.youtube.com/watch?v=wyyCHDZ1qww) 

Then replace the empty string key with the api key Facebook gives you.

**Comment by KartikBazzad** [comment]
@CJMobileApps  thanks man i figured it out....

**Comment by CJMobileApps** [comment]
@KartikBazzad great!
